apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: library-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: afc20c5360fa344718ab7cfaf1ab0770-1341063792.ap-south-1.elb.amazonaws.com

      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: library-frontend-service
                port:
                  number: 3005
