apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: library-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: library.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: library-frontend-service
                port:
                  number: 3005
